swagger: '2.0'
info:
  title: ZSSN API
  description: Move your app forward with the Uber API
  version: "1.0.0"
host: 127.0.0.1
schemes:
  - http
  - https
basePath: /api
produces:
  - application/json
paths:
  /survivor:
    post:
      summary: Register a new survivor.
      description: |
        Receive a Person with its Inventory of Items.
      parameters:
        - name: person[name]
          in: query
          description: Survivor Full Name.
          required: true
          type: string
        - name: person[age]
          in: query
          description: Survivor Age.
          required: true
          type: string
        - name: person[gender]
          in: query
          description: Survivor Gender.
          required: true
          type: string
        - name: person[lonlat]
          in: query
          description: Survivor latitude x longitude in the format 'point(-0000.111, 1111.000)'.
          required: false
          type: string
        - name: items
          in: query
          description: Inventory Items in the format 'Water:10;Food:5'.
          required: true
          type: string
      tags:
        - Survivor
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/survivor'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
